# Development profile
spring.datasource.url=${DEV_DB_URL:}
spring.datasource.username=${DEV_DB_USERNAME:}
spring.datasource.password=${DEV_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS
app.security.cors.allowed-origins=${DEV_CORS_ALLOWED_ORIGINS:}

app.security.cookie.same-site=${PROD_COOKIE_SAME_SITE:}
app.security.cookie.secure=${PROD_COOKIE_SECURE:}
app.security.cookie.domain=${PROD_COOKIE_DOMAIN:}
app.security.cookie.path=${PROD_COOKIE_PATH:/}

# Admin bootstrap (supports both dev/prod)
app.bootstrap.admin.enabled=${DEV_BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap.admin.full-name=${DEV_BOOTSTRAP_ADMIN_FULL_NAME:System Administrator}
app.bootstrap.admin.email=${DEV_BOOTSTRAP_ADMIN_EMAIL:admin@acare.local}
app.bootstrap.admin.phone=${DEV_BOOTSTRAP_ADMIN_PHONE:0975769006}
app.bootstrap.admin.id-number=${DEV_BOOTSTRAP_ADMIN_ID_NUMBER:0605009361}
app.bootstrap.admin.address=${DEV_BOOTSTRAP_ADMIN_ADDRESS:284 Te Lo, Phu Tho}
app.bootstrap.admin.password=${DEV_BOOTSTRAP_ADMIN_PASSWORD:ChangeMe@123}

logging.level.root=DEBUG
